### ISSUE TITLE
[Enhancement]: Améliorer les retours de l'API - Atteinte de limit de 10 test/j/domain

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_bff#18]
# Atteinte de limit de 10 test/j/domain
J'ai une erreur 500, pas d'infos et l'extension chrome ne sait pas gérer, car elle mouline dans vide...
## Proposition
- code erreur:  [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)
- message: Le domain https://www.yourdomain.tld/test a atteint le nombre des `n` mesures proposées par Ecoindex pour la journée du DD/MM/YY
- nombre de tests restants sur ce domain pour cette journée (parfois, il faut lire le header de la response - je ne retrouve pas ça dans la doc -, parfois le body, simplifiez la vie en mettant tout dans le body et pourquoi pas dupliquez dans le header).
```json
{
  "code": 429,
  "message": "Le domain https://www.yourdomain.tld/test a atteint le nombre des `n` mesures proposées par Ecoindex pour la journée du DD/MM/YY",
  "remaining-daily-requests": 3,
  "count": 17,
  "latest-result": {
    "id": "",
    "grade": "",
    "score": 0,
    "date": "",
    "requests": 0,
    "size": 0,
    "nodes": 0,
    "url": "",
    "color": ""
  },
  "older-results": null,
  "host-results": [
    {
      "id": "46df881f-0cc3-4153-9fa9-871f65b22362",
      "grade": "B",
      "score": 74,
      "date": "2023-03-21T22:30:57",
      "requests": 39,
      "size": 1210.65,
      "nodes": 264,
      "url": "https://novagaia.fr/offres/creez-un-site-web-performant-et-moins-polluant/",
      "color": "#51B84B"
    },
    {
      "id": "430b0d3c-0bd2-4b75-bdea-8d410f2615d3",
      "grade": "B",
      "score": 72,
      "date": "2023-03-21T22:29:10",
      "requests": 55,
      "size": 779.939,
      "nodes": 273,
      "url": "https://novagaia.fr/",
      "color": "#51B84B"
    },
    // ...
  ]
}
```

**Comment by vvatelot** [comment]
Le problème a été corrigé.
Peux tu vérifier et me confirmer ?

**Comment by hrenaud** [comment]
oui, c'est bon, il y a bien le code erreur 429
