### ISSUE TITLE
[Enhancement]: Améliorer les retours de l'API - Demande de mesure d'une URL

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_bff#19]
# Demande de mesure d'une URL
Pourquoi recevoir un numéro de task (ce devrait être du json), plutôt qu'attendre et retourner l'arbre ?
```json
"35c64f8e-9bca-4c0d-b5db-9dda4d1c6fe5"
```
## Proposition
- renvoyer le code [201](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201)
- renvoyer l'arbre rempli par le test courant dans `result` ;
- indiquer le nombre de test restant dans `remaining-daily-requests`.
```json
{
  "code": 201,
  "remaining-daily-requests": 4,
  "count": 17,
  "result": {
      "id": "46df881f-0cc3-4153-9fa9-871f65b22362",
      "grade": "B",
      "score": 74,
      "date": "2023-03-21T22:30:57",
      "requests": 39,
      "size": 1210.65,
      "nodes": 264,
      "url": "https://novagaia.fr/offres/creez-un-site-web-performant-et-moins-polluant/",
      "color": "#51B84B"
    },
}
```

**Comment by vvatelot** [comment]
Hello, j'avais répondu à ta question dans ce commentaire: :wink:
https://github.com/cnumr/ecoindex_api/issues/309#issuecomment-1479824463

Après, je peux te donner un peu plus d'infos sur ce [post linkedin](https://www.linkedin.com/posts/vincent-vatelot-7a31149_numaezriqueresponsable-assogreenit-ecoindex-activity-7004027697228054528-jlKn/)

Voilà le fonctionnement actuel pour expliquer ce qu'il se passe:
![image](https://user-images.githubusercontent.com/12939091/227148829-77eff13e-670d-468d-a66a-7f9a03b119ec.png)

**Comment by hrenaud** [comment]
dans ton commentaire, tu parlais de la tache https://cors.redoc.ly/v1/tasks/ecoindexes (qui ne s'appelle plus comme ça)
là je parle de la suivante, celle où je passe l'id et je demande le résultat.
Comme je tombe en erreur, il faut que je lise quand même le résultat pour lire le status et je boucle pour réessayer plus tard. Ce sont des appels reseaux pour rien, ce qui n'est pas recommandé par le greenIT, non ;)

**Comment by vvatelot** [comment]
425 = [Too early](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/425)

C'est un code standard HTTP: La tâche n'a pas encore été traitée, il faut donc réessayer plus tard (en moyenne, 15sec, mais peut être plus long si bcp de tâches en attentes de traitement)

Tant que la tâche n'est pas traitée, on renvoie ce code erreur et lorsqu'elle a été traitée, on renvoie une 200 avec le résultat

**Comment by hrenaud** [comment]
ça génère une erreur dans la console du navigateur, c'est dommage.
